### ISSUE TITLE
Basic case not working.

### ISSUE THREAD

**Issue by PaulMaly** [domvm/domvm#198] opened 2018-06-07 08:51 UTC
I use v.3.3.2. Basic case with View not working for me:

```javascript
const el = domvm.defineElement;

function Hello(vm) {
    return (vm, data) => {
        return el(`div`, `Hello ${data.name}`);
    }
}

const data = {
    name: `World`
};

const vm = domvm.createView(Hello, data);

vm.mount(document.getElementById('app'));
```

In devtools I see that ```div``` element added to container ```#app```, but it's empty.

What I'm doing wrong?

**Comment by PaulMaly** [comment] 2018-06-07 09:06
After I switched back to v3.2.8, the example now working fine. Maybe some breaking changes appear in last versions and docs need to be updated?

**Comment by leeoniya** [comment] 2018-06-08 05:50
hey @PaulMaly 

i am not able to reproduce your issue.

v3.3.2 (nano build): https://jsfiddle.net/0c1we9np/
v3.2.8 (nano build): https://jsfiddle.net/0c1we9np/1/

both seem to work okay.

**Comment by sloosch** [comment] 2018-06-10 11:34
@leeoniya 
ran into the same issue. full and dev build seems not to work.

**Comment by leeoniya** [comment] 2018-06-10 17:32
you guys are right 😧.

looks like a regression introduced in the streams feature rewrite. the reason the tests didnt catch something so seemingly obvious is that the tests only run against the full build with all features utilized, so a flyd stream adapter is always defined to test streams. however when no stream adapter is provided the default value getter went from returning the passed value to a noop (returning undefined).

should be fixed in latest commit: https://jsfiddle.net/0c1we9np/3/

i'll cut a new build later today.

**Comment by leeoniya** [comment] 2018-06-11 04:51
v3.3.3 is published. closing this, but feel free to re-open if issues persist.

thanks!

**Closed by leeoniya** 2018-06-11 04:51 UTC
